internal/pprof/label.go
internal/pprof/protomem.go
pkg/profile/profile.go
pkg/profile/repository.go
pkg/storage/postgres/labels.go
pkg/storage/postgres/postgres.go
pkg/storage/postgres/sql.go
pkg/storage/postgres/sql/init.sql

Plus
- get rid of `received_at` column; it wasn't used anyway, so we can save some storage space
- fix typo in heap profile builder

storage/postgres: store and retrieve sample labels

---

agent/agent.go
agent/options.go

- CPU profiling enabled by default
- only heap and CPU profiling support by server; disable the rest in agent
- dis-align initial profiling by adding extra N seconds of sleep

agent: send supported profiles

---

pkg/profefe/profiles_handler.go
pkg/profefe/querier.go
pkg/storage/badger/badger.go
pkg/storage/badger/integration_test.go
pkg/storage/storage.go

Get rid of `io.EOF`, which felt awkward. Make the API more like a conventional iterator in Go. I.e.
```go
list := getProfilesList()
defer list.Close()
for list.Next() {
p, err := list.Profile()
}
```
Also, have adjusted naming in internal methods.

pkg/storage: update ProfileList iterator API

---

pkg/profefe/collector.go
pkg/profefe/profile.go
pkg/profefe/profiles_handler.go
pkg/profefe/querier.go
pkg/profefe/reply.go
pkg/profefe/reply_test.go
pkg/profile/profile.go
pkg/profile/profile_type.go
pkg/profile/profile_type_test.go
pkg/storage/badger/badger.go
pkg/storage/badger/integration_test.go
pkg/storage/storage.go

closes #41 
@gianarb Could you verify that it solves your use case?
```http
> POST /api/0/profiles?service=profefe&instance_id=imported-profile&type=cpu&labels=host=localhost,az=home
<
{
"code": 200,
"body": {
"id": "bnfbubnbudgj1mo98i3g",
"type": "cpu",
"service": "profefe",
"labels": [
{
"key": "az",
"value": "home"
},
{
"key": "host",
"value": "localhost"
}
],
"created_at": "2019-11-27T18:23:42.334459Z"
}
}
```
```http
> GET /api/0/profiles?service=profefe&type=cpu&from=2019-01-25T00:00:00&to=2019-11-30T00:00:00
<
{
"code": 200,
"body": [
{
"id": "bnfah9fbudgif8og0bmg",
"type": "cpu",
"service": "profefe",
"labels": [
{
"key": "az",
"value": "home"
},
{
"key": "host",
"value": "localhost"
}
],
"created_at": "2019-05-30T23:14:00.707996+02:00"
},
{
"id": "bnfah0vbudgif8og0bm0",
"type": …
```

Respond with profile data on creation

---

agent/agent.go
agent/options.go
examples/server/main.go

Following #45 
The PR adds a new option to `profefe/agent` — `agent.WithThreadcreateProfile()` — that enables collecting "stack traces that led to the creation of new OS threads" (see https://golang.org/pkg/runtime/pprof/#Profile)

agent: support for threadcreate profiles

---

README.md
agent/agent.go
pkg/profefe/collector.go
pkg/profefe/request.go
pkg/profile/profile.go
pkg/storage/badger/integration_test.go
scripts/pprof_import.sh

`instance_id` was an artefact from the earlier prototypes of profefe. It helped to simplify the first version of storage, which was based on PostgreSQL (refer to https://github.com/profefe/profefe/pull/28 why it didn't work).
As it's now `instance_id` is a rudiment that is never stored and doesn't do anything.

pkg/profile: get rid of instance_id

---

README.md
pkg/profefe/querier.go
pkg/profefe/routes.go
pkg/profefe/services_handler.go
pkg/profefe/services_handler_test.go
pkg/storage/badger/badger.go
pkg/storage/badger/cache.go
pkg/storage/badger/integration_test.go
pkg/storage/mock.go
pkg/storage/storage.go

Return list of services

---

.travis.yml
Makefile
scripts/ci_build_image.sh

On push to `master`, Travis CI runs the deploy build stage that builds docker image for specified platforms (using [buildkit][1]) and pushes the image to docker hub.
[1]: https://github.com/moby/buildkit

ci: build docker image with buildkit on push to master

---

pkg/profefe/querier.go
pkg/profefe/querier_test.go

If the request to `api/0/profiles/merge` is closed while collector is still reading profiles from the storage, `Querier` can bailout, returning `context.Canceled` error.
If the same request is closed after all profiles were read, `Querier` will fail with `"write: broken pipe"` when it will try to write the result to the client. Note, this is still not perfect, e.g. if merging takes more time than reading profiles from storage.

Allow Querier to bail out from FindMergeProfileTo if context was cancelled

---

README.md
pkg/profefe/profiles_handler.go
pkg/profefe/querier.go
pkg/profefe/querier_test.go
pkg/profile/profile.go
pkg/profile/profile_test.go
pkg/storage/stub.go

The PR updates `/api/0/profiles` API to allow passing multiple profile IDs (using `+` as ids' separator):
```
GET /api/0/profiles/id1+id2+id3
```
The API returns a single profile, that contains all profiles merged into one. 
This change effectively makes `/api/0/profiles/merge?service=svc1` an alias for
```
> GET /api/profiles?service=svc1 | jq '.body | .[] | .id'
id1
id2
id3
> GET /api/profiles/id1+id2+id3
```

Update get profile API to allow merging profiles by IDs

---

pkg/storage/s3/s3.go

As we've discussed with @gianarb there is no need for limiting `ListServices` as this already lead to missing services in some setups.

storage/s3: don't limit number of returned services

---

pkg/storage/s3/s3.go

Apparently S3 is not filtering profiles that are too old. This PR fixes
this issue.
Fixed #82
Signed-off-by: Gianluca Arbezzano <gianarb92@gmail.com>

fix(s3): s3 returns profiles too old via the get profiles API

---

pkg/profile/labels.go
pkg/storage/s3/s3.go

A tiny optimisation in s3 Writer.
Extra: encode `/` in service names as `__`, to help with troubleshooting.

pkg/profile: implement LabelsEncoder

---

agent/agent.go
agent/options.go
agent/retry.go
agent/retry_test.go

The option sets how often agent scraps profiling data from the application.
Also fixes agent's retry mechanics, by specifying the max number of retry attempts (hardcoded for now).

Add agent.WithTickInterval option

---

cmd/profefe/main.go
pkg/agentutil/confg.go
pkg/config/config.go
pkg/profile/labels.go

Add a set of flags to configure agent to read profiling data and send the data to collector's public address. That is
```
$ profefe -addr='localhost:10100' -badger.dir=data \
-profefe.agent.collector-addr='http://localhost:10100' \
-profefe.agent.service-name='profefe-collector' \
-profefe.agent.labels='region=eu,dc=ber,host=localhost' \
-profefe.agent.read-interval=1m \
-profefe.agent.enable-cpu-profile=10s \
-profefe.agent.enable-heap-profile
```

Allow collector to read profiling data via agent

---

pkg/storage/clickhouse/schema/profefe.sql

Refer to https://github.com/google/pprof/blob/master/proto/profile.proto
Sample's values are `repeated int64 value`

Fix typo in ClickHouse storage schema

---

README.md
pkg/profefe/profiles_handler.go
pkg/profefe/request.go
pkg/profile/profile.go
pkg/storage/clickhouse/reader.go
pkg/storage/storage.go

closes #99 
```
› curl -s 'http://localhost:10100/api/0/profiles?service=refresh_worker&from=2020-06-08T00:00:00&to=2020-06-08T23:59:00&limit=2' | jq -c '.body | .[].type'
"cpu"
"heap"
```

Call query API with out "type" parameter

---

pkg/profefe/metrics.go

Requests to save profiles API shouldn't be labelled as ID-based.

pkg/profefe: fix api metrics label

---

contrib/docker/Dockerfile

1.15.2 has [a good bunch of fixes][1] in runtime and compiler. So guess it's worth bumping the version once again.
[1]: https://github.com/golang/go/issues?q=milestone%3AGo1.15.2+label%3ACherryPickApproved

Update docker image to Go 1.15.2

---

.travis.yml
docker-compose.yml

As it was raised in #119 tests for `storage/clickhouse` fail for ClickHouse server newer than 20.8. I'd like to specify the known working version for now to make the tests pass and will look into the changes in CH later.

testing: specify clickhouse version in docker-compose
